### ISSUE TITLE
ReadME file

### ISSUE THREAD

**Issue by nurlanotek** [kamiajo/comsite#1]
Update README file:

- [x] the numbered list of team members with full name and surname  @kamiajo 
- [x] project roles of each team member @aba-bakri @kamiajo @Gullzat

**Comment by nalrun** [comment]
The first part of the issue is not complete. It's supped to be numbered list.

**Comment by nalrun** [comment]
Accepted.

**Comment by nalrun** [comment]
I can't close the issue, because I am not part of contributors.
I have to GitHub accounts. The right one is "nalrun" with "nurlan.shaidullaev@iaau.edu.kg" email.
